#!/usr/bin/env python3
"""Generate src/GrainLUT.h: a per-level grain-gain LUT so the model's output RMS
tracks the measured 500T scan at every exposure.

gain(u) = scanRMS_green(u) / modelCoverageRMS(u)

With this gain applied to the grain fluctuation, output RMS at level u equals
scanRMS(u) when Amount = 1. The model's coverage RMS is single-humped (peaks at
mid); the scan is U-shaped; the LUT reconciles them.
"""
import numpy as np, subprocess, os

# Measured green-channel grain RMS vs level (temporal, from analyze_grain.py),
# with endpoints: 0 grain at black, gentle hold into the highlight.
pts_u = [0.00, 0.104, 0.147, 0.206, 0.279, 0.415, 0.543, 0.75, 1.00]
pts_r = [0.00, 0.01346, 0.00938, 0.00854, 0.00942, 0.01446, 0.01549, 0.0158, 0.0150]

N = 33
us = np.linspace(0.0, 1.0, N)
target = np.interp(us, pts_u, pts_r)

# Soft-kernel model: the fluctuation is normalized to ~unit variance independent
# of radius, so gain(u) ~= scanRMS(u). Calibrate at the shipped defaults.
R, SIGMA, NS, SZ = 0.85, 0.0, 1, 256
cov = np.zeros(N)
for i, u in enumerate(us):
    if u <= 0.0:
        cov[i] = 0.0; continue
    lvl = min(u, 0.999)
    subprocess.run(["./calib_field", str(R), str(SIGMA), str(NS), str(lvl), str(SZ), "/tmp/lut.bin"],
                   check=True, capture_output=True)
    cov[i] = float(np.fromfile("/tmp/lut.bin", dtype=np.float32).std())

# gain; suppress where there is essentially no grain (pure black/white).
gain = np.where(cov > 0.02, target / np.maximum(cov, 1e-6), 0.0)
gain = np.clip(gain, 0.0, 0.2)
flat = float(np.interp(0.5, us, gain))  # mid-tone gain == flat-mode scale

print(" u      target   coverage  gain")
for i in range(N):
    print(f" {us[i]:.3f}  {target[i]:.5f}  {cov[i]:.4f}   {gain[i]:.5f}")
print(f"\nflat-mode scale (gain@0.5) = {flat:.5f}")

hdr = []
hdr.append("// GrainLUT.h - AUTO-GENERATED by tools/make_lut.py. Do not edit by hand.")
hdr.append("// Per-level grain-gain LUT matching the Kodak 500T grey-card scan.")
hdr.append("// gain(u) = scanRMS_green(u) / modelCoverageRMS(u); output RMS = Amount * gain(u) * coverageRMS(u).")
hdr.append("#ifndef FILMGRAIN_GRAINLUT_H")
hdr.append("#define FILMGRAIN_GRAINLUT_H")
hdr.append(f"static const int   kGainLUTSize = {N};")
hdr.append(f"static const float kGainFlatScale = {flat:.6f}f;  // mid-tone gain, used when Match Curve is off")
hdr.append("static const float kGainLUT[%d] = {" % N)
for i in range(0, N, 6):
    chunk = ", ".join(f"{gain[j]:.6f}f" for j in range(i, min(i+6, N)))
    hdr.append("    " + chunk + ("," if i+6 < N else ""))
hdr.append("};")
hdr.append("#endif // FILMGRAIN_GRAINLUT_H")

open("src/GrainLUT.h", "w").write("\n".join(hdr) + "\n")
print("\nwrote src/GrainLUT.h")
