// GrainLUT.h - AUTO-GENERATED by tools/make_lut.py. Do not edit by hand.
// Per-level grain-gain LUT matching the Kodak 500T grey-card scan.
// gain(u) = scanRMS_green(u) / modelCoverageRMS(u); output RMS = Amount * gain(u) * coverageRMS(u).
#ifndef FILMGRAIN_GRAINLUT_H
#define FILMGRAIN_GRAINLUT_H
static const int   kGainLUTSize = 33;
static const float kGainFlatScale = 0.014975f;  // mid-tone gain, used when Match Curve is off
static const float kGainLUT[33] = {
    0.000000f, 0.004080f, 0.008123f, 0.012253f, 0.011561f, 0.009321f,
    0.008896f, 0.008727f, 0.009101f, 0.009487f, 0.010630f, 0.011745f,
    0.012899f, 0.014024f, 0.014485f, 0.014725f, 0.014975f, 0.015215f,
    0.015355f, 0.015450f, 0.015517f, 0.015579f, 0.015569f, 0.015606f,
    0.015701f, 0.015613f, 0.015454f, 0.015373f, 0.015280f, 0.015186f,
    0.015124f, 0.014939f, 0.015048f
};
#endif // FILMGRAIN_GRAINLUT_H
